name: "rspec spec/"

on:
  push:
    branch:
      - master
    paths:
      - 'lib/**'
      - 'spec/**'
      - '.github/workflows/rspec.yaml'
  schedule:
    - cron: '0 11 */4 * *'

jobs:
  Test-Proxy-SendMail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 環境変数から暗号化ファイルの鍵を取り出し。
        run: |
          pwd
          echo 環境変数のメモ
          echo expected variables
          echo Google-GCP-OAUTH2-client
          echo "---------------------------"
          echo "--- client_secret"
          echo "---------------------------"
          echo "SPEC_ENC_KEY=${{ secrets.SPEC_ENC_KEY }}"
          export SPEC_ENC_KEY=${{ secrets.SPEC_ENC_KEY }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: 3.1
      - name: bundle install
        run: |
          bundle install
          bundle
      - name: rspecテスト
        run:
          bundle exec rspec spec/
